SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Saddle Brother"
CHARACTER_SCALING = 1.0
IMAGE_SIZE = 64.0
MAP_COUNT_X = 40
MAP_COUNT_Y = 40

# Screen values
GAME_WIDTH = IMAGE_SIZE * MAP_COUNT_X
GAME_HEIGHT = IMAGE_SIZE * MAP_COUNT_Y

VIEWPORT_MARGIN_HORT = SCREEN_WIDTH / 2 - IMAGE_SIZE * 2
VIEWPORT_MARGIN_VERT = SCREEN_HEIGHT / 2 - IMAGE_SIZE * 2

# Ascii values
EMPTY = ' '
WALL = '#'
AGENT = '@'
GOAL = 'x'
GRASS = 'g'
WATER = 'w'

